### ISSUE TITLE
Feature request: multiple dirs

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/global-components#10]
Multiple dirs could be handy eg if you use a shared component lib outside your nuxt root.

**Comment by nonlinearcom** [comment]
Hi, do you have an example on how to use dirs? I'm my case they didn't work on components without the .global.{ext} 
Thanks!

**Comment by ricardogobbosouza** [comment]
Hi @nonlinearcom 
This module makes an join of options:
`dir/*.suffixes.extensions` = `components/*.global.vue`

with multiple dirs the join is the same:
`dir[0]/*.suffixes.extensions` = `components/*.global.vue`
`dir[1]/*.suffixes.extensions` = `other-dir/*.global.vue`

**Comment by ricardogobbosouza** [comment]
Maybe you need to disable `suffixes`, just leave empty:
```js
// nuxt.config.js
export default {
  buildModules: [
    '@nuxtjs/global-components'
  ],
  globalComponents: {
    dir: ['components', 'other-dir']
    suffixes: []
  }
}
```
With this configuration above, these will be the search locations:
- `components/**/*.vue`
- `other-dir/**/*.vue`
