### ISSUE TITLE
Components are not being registered when mangled by Webpack

### ISSUE THREAD

**Issue by miii** [nuxt-community/global-components#2]
Webpack mangles prototype names to `t` or similar in production environments, which prevents this plugin from working. This can be resolved using `mangle.keep_fnames` in the Webpack config.

However, it would be great to add an option to this package to simply ignore name detection using prototype names, or possibly ignore it by default to make it work with the default Nuxt config.
https://github.com/nuxt-community/global-components/blob/f913114d6025885f2ee3c374496018f76b6ce692/lib/plugin.js#L5

What's your thoughts?

**Comment by ricardogobbosouza** [comment]
Hi @miii 
We can think of an option to ignore name detection
