### ISSUE TITLE
Nuxt Warning

### ISSUE THREAD

**Issue by nonlinearcom** [nuxt-community/global-components#9]
Hi, I noticed this Nuxt warning while i running build or generate commands:
```
⚠ Nuxt Warning                                                                     
                                                                                         
      The command 'nuxt build' finished but did not exit after 5s                        
      This is most likely not caused by a bug in Nuxt.js                                 
      Make sure to cleanup all timers and listeners you or your plugins/modules start.   
      Nuxt.js will now force exit                                                        
                                                                                        
      DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error  
```

I got it right after cloning and updating the project on the readme page: https://codesandbox.io/s/nuxtjs-global-components-ujtoq

![Screenshot 2020-01-19 at 09 36 37](https://user-images.githubusercontent.com/7942973/72677680-42042380-3a9f-11ea-834a-d19fe2846d7f.png)

Is there any way to get rid of this warning?

**Comment by pi0** [comment]
Thanks for the report! Should be fixed in [v0.4.1](https://github.com/nuxt-community/global-components/blob/master/CHANGELOG.md#041-2020-01-19)
